# -*- coding: utf-8 -*-
"""Text Extractor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vxxDLW5AISErxieU78Ux2vV-SSwhcBaO
"""

#SE USARON DOS METODOS: TXTExtractor1 QUE UTILIZA EXPRESIONES REGULARES PARA LIMPIAR LAS COLUMNAS 
#Y TXTExtractor2 QUE UTILIZA LA POSICIÓN DE LAS COLUMNAS CON BASE A LA PRIMERA LÍNEA DEL TEXTO

import csv
import pandas as pd
import re
import numpy as np

class TXTExtractor1:
    @staticmethod
    def run1(file):
        final = []
        columns = ['marca', 'tipo', 'ubicación', 'placa']

        with open(file, 'r') as archivo:
            for fila in map(lambda x: re.sub(r'(\s){2,}', ',', x), archivo):
                extractor = csv.reader([(fila)], delimiter = ',')
                final.extend(list(extractor))
                df = pd.DataFrame(final, columns = columns)
            if df['placa'].isnull().any():
                df['placa'] = df['placa'].fillna(df['ubicación'].str.extract(r'(\d+)', expand=True).squeeze()).astype(str)
                df['ubicación'] = df['ubicación'].str.replace(r'(\d+)', '')
            if df['ubicación'].isnull().any():
                mayus = next((i for i, c in enumerate(df['tipo']) if c.isupper()), '')
                a_extraer = df['tipo'][mayus] if mayus else ''
                df['ubicación'] = df['ubicación'].fillna(a_extraer)
                df['tipo'] = df['tipo'].str.replace(a_extraer, '')
            else:
                pass

        df['fecha'] = pd.Timestamp('2019-07-06').strftime('%d/%m/%Y')
        df['consecutivo'] = df.index+1
        df = df.astype(str)
        df.to_csv('punto2.csv',sep=',', encoding='utf-8-sig', index=False)
        return df


class TXTExtractor2:
    @staticmethod
    def run2(file):
        lista = []
        columns = ['marca', 'tipo', 'ubicación', 'placa']

        with open(file, 'r') as archivo:
            primera_linea = archivo.readline()
            lineas = [primera_linea] + archivo.readlines()
            #AL SER DE CARÁCTERES FIJOS, SE USAN LOS DATOS DE LA PRIMERA LINEA DEL .TXT
            referencia = len(primera_linea)
            tipo_pos = primera_linea.find('Diesel')
            ubicacion_pos = primera_linea.find('Galicia')
            placa_pos = primera_linea.find('0001')
            posiciones = [  (0, tipo_pos), 
                            (tipo_pos, ubicacion_pos), 
                            (ubicacion_pos, placa_pos), 
                            (placa_pos, referencia)]
            for linea in lineas:
                fila = [linea[start:end].strip() for start, end in posiciones]
                lista.append(fila)
            df = pd.DataFrame(lista, columns=columns)
            df['fecha'] = pd.Timestamp('2019-07-06').strftime('%d/%m/%Y')
            df['consecutivo'] = df.index+1
            df = df.astype(str)
            df.to_csv('punto2.csv',sep=',', encoding='utf-8-sig', index=False)
            return df